<a href="https://colab.research.google.com/github/musowjanya/Deep-Learning/blob/main/batch_convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
ar = np.array([3,5,6,2,1,5])

In [ ]:
np.convolve(ar, [1,2,3]) # (3,2,1)

array([ 3, 11, 25, 29, 23, 13, 13, 15])

In [ ]:
from sklearn.datasets import load_digits

In [ ]:
dt = load_digits(n_class=3)

In [ ]:
dt.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [ ]:
dt.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [ ]:
dt.images.shape

(537, 8, 8)

In [ ]:
X = dt.images
Y = dt.target

In [ ]:
X = X.reshape(537,1,8,8)

In [ ]:
import torch
import torch.nn as nn
from torch.optim import Adam

In [ ]:
X = torch.FloatTensor(X)
Y = torch.LongTensor(Y)

In [ ]:
X.shape

torch.Size([537, 1, 8, 8])

In [ ]:
model = nn.Sequential(
    nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2, stride=2),
    nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=2, stride=2),
    nn.Flatten(),
    nn.Linear(64*2*2, 128),
    nn.ReLU(),
    nn.Linear(128, 3)
)

In [ ]:
loss = nn.CrossEntropyLoss()
opt = Adam(model.parameters(), lr=0.001)

In [ ]:
loss = nn.CrossEntropyLoss()
opt = Adam(model.parameters(), lr=0.001)

In [ ]:
from torch.utils.data import TensorDataset, DataLoader

In [ ]:
dataset = TensorDataset(X, Y)
batch_size = 32
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [ ]:
for batch_X, batch_Y in dataloader:
    break
batch_X.shape

torch.Size([32, 1, 8, 8])

In [ ]:
len(dataloader.dataset)

537

Using Batch Process

In [ ]:
model.train()
c=0
for epoch in range(100):
    c=c+1
    epoch_loss = 0.0
    for batch_X, batch_Y in dataloader:
        opt.zero_grad()
        yp = model(batch_X)
        ls = loss(yp, batch_Y)
        ls.backward()
        opt.step()
        epoch_loss += ls.item()

    if c%10==0:
      print(epoch_loss)


0.013565746645326726
0.0027146952525072265
0.0010333370346415904
0.0005682349215021532
0.00032156060569832334
0.00021519437564165855
0.0001511550894974789
0.00011448027635196922
8.615504782483185e-05
6.751201613042213e-05


In [ ]:
newx = X[112].reshape(1,1,8,8)

In [ ]:
newx.shape

torch.Size([1, 1, 8, 8])

In [ ]:
Yp = model(newx)

In [ ]:
sx = torch.softmax(Yp, dim=1)

In [ ]:
torch.argmax(sx, dim=1)

tensor([1])

Class based Model

In [ ]:
import torch.nn as nn
from torch.optim import Adam

In [ ]:
class MyNet(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
    self.maxm = nn.MaxPool2d(kernel_size=2, stride=2)
    self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
    self.relu = nn.ReLU()
    self.flatten = nn.Flatten()
    self.linear1 = nn.Linear(64*2*2, 128)
    self.linear2 = nn.Linear(128, 3)

  def forward(self, x):
    x = self.conv1(x)
    x = self.relu(x)
    x = self.maxm(x)
    x = self.conv2(x)
    x = self.relu(x)
    x = self.maxm(x)
    x = self.flatten(x)
    x = self.linear1(x)
    x = self.relu(x)
    x = self.linear2(x)
    return x

In [ ]:
class MyNet(nn.Module):
  def __init__(sf):
    super().__init__()
    sf.conv1 = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=1)
    sf.maxm = nn.MaxPool2d(kernel_size=2, stride=2)
    sf.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
    sf.relu = nn.ReLU()
    sf.flatten = nn.Flatten()
    sf.linear1 = nn.Linear(64*2*2, 128)
    sf.linear2 = nn.Linear(128, 3)

  def forward(sf, x):
    x = sf.conv1(x)
    print(x.shape)
    x = sf.relu(x)
    x = sf.maxm(x)
    x = sf.conv2(x)
    x = sf.relu(x)
    x = sf.maxm(x)
    x = sf.flatten(x)
    x = sf.linear1(x)
    x = sf.relu(x)
    x = sf.linear2(x)
    return x

In [ ]:
mod = MyNet()

In [ ]:
mod(X)

torch.Size([537, 32, 8, 8])


tensor([[-0.5625, -0.4439,  0.4721],
        [-0.2758, -0.6131,  0.2881],
        [-0.5424, -0.4707,  0.1721],
        ...,
        [-0.4377, -0.3748,  0.1142],
        [-0.2723, -0.4526, -0.0650],
        [-0.7048, -0.4249,  0.4108]], grad_fn=<AddmmBackward0>)

In [ ]:
loss = nn.CrossEntropyLoss()
opt = Adam(mod.parameters(), lr=0.001)

In [ ]:
c=0
for epoch in range(100):
    c=c+1
    opt.zero_grad()
    yp = mod(X)
    ls = loss(yp, Y)
    ls.backward()
    opt.step()
    if c%10==0:
      print(ls.item())

torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
0.2978546619415283
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
0.05530047044157982
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
0.013969829306006432
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537, 32, 8, 8])
torch.Size([537,