<a href="https://colab.research.google.com/github/musowjanya/DL_Mini_Projects/blob/main/iris_training_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [91]:
from sklearn.datasets import load_iris

In [92]:
import numpy as np
import pandas as pd

In [93]:
import torch
import torch.nn as nn
import torch.optim as optim

In [94]:
dt=load_iris()

In [95]:
dt.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [96]:
X,Y=dt.data,dt.target

In [97]:
dt.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [98]:
model=nn.Sequential(
    nn.Linear(4,30),
    nn.ReLU(),
    nn.Linear(30,10),
    nn.ReLU(),
    nn.Linear(10,3),
    # nn.Softmax(dim=1)
)

In [99]:
X=torch.FloatTensor(X)
Y=torch.LongTensor(Y)

In [100]:
# model(X) #output is three colomns because of three target classes

In [101]:
# torch.argmax(model(X),dim=1)

In [102]:
# lossfn=nn.LogSoftmax()
lossfn=nn.CrossEntropyLoss()
optsgd=optim.SGD(model.parameters(),lr=0.01)

Training

In [103]:
for _ in range(100):
  yp=model(X)
  loss=lossfn(yp,Y)
  loss.backward()
  optsgd.step()

  print(loss.item())

1.0983588695526123
1.0970057249069214
1.0944674015045166
1.0910358428955078
1.0870548486709595
1.0828299522399902
1.078551173210144
1.0742405652999878
1.0697331428527832
1.0646997690200806
1.0587018728256226
1.0512644052505493
1.0419564247131348
1.03044855594635
1.0165148973464966
1.000044345855713
0.9809966087341309
0.9598234295845032
0.9391577243804932
0.9183019995689392
0.8912994265556335
0.859096348285675
0.8283092379570007
0.8010110259056091
0.7710687518119812
0.7340167760848999
0.6918985843658447
0.6519827246665955
0.6130516529083252
0.5741419792175293
0.536521852016449
0.5013659000396729
0.46950092911720276
0.4411035180091858
0.41571348905563354
0.3923261761665344
0.3700156509876251
0.34885072708129883
0.33012959361076355
0.3142169117927551
0.2977079749107361
0.2763577997684479
0.2527146637439728
0.23461751639842987
0.21973203122615814
0.19721797108650208
0.17404700815677643
0.16163362562656403
0.14658190310001373
0.1262490600347519
0.1186484768986702
0.11207800358533859
0.09593

Inference

In [104]:
ynewp=model(X)

In [105]:
sfout=torch.softmax(ynewp,dim=1)

In [146]:
torch.argmax(sfout,dim=1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2,
        2, 2, 2, 2, 2, 2])

Using Batches

In [107]:
from torch.utils.data import DataLoader

In [108]:
df=pd.DataFrame(X)

In [109]:
df

,0,1,2,3
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [111]:
df['Y']=Y

In [121]:
df=torch.tensor(df.numpy())

In [124]:
model = nn.Sequential(
    nn.Linear(4, 30),
    nn.ReLU(),
    nn.Linear(30, 10),
    nn.ReLU(),
    nn.Linear(10, 3),
    # nn.Softmax(dim=1)
)

In [145]:
lossfn = nn.CrossEntropyLoss()
batchSgd = optim.SGD(model.parameters(), lr=0.01)

In [144]:
batches=DataLoader(df,batch_size=10, shuffle=True)

In [116]:
# for batch in batches:
#   X=batch[:,:-1]
#   Y=batch[:,-1]

#   print(X,Y)

tensor([[4.8000, 3.1000, 1.6000, 0.2000],
        [5.1000, 3.8000, 1.9000, 0.4000],
        [5.4000, 3.7000, 1.5000, 0.2000],
        [6.9000, 3.1000, 5.1000, 2.3000],
        [6.0000, 2.7000, 5.1000, 1.6000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [4.9000, 2.4000, 3.3000, 1.0000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [6.1000, 3.0000, 4.6000, 1.4000],
        [7.6000, 3.0000, 6.6000, 2.1000]], dtype=torch.float64) tensor([0., 0., 0., 2., 1., 0., 1., 0., 1., 2.], dtype=torch.float64)
tensor([[5.0000, 3.3000, 1.4000, 0.2000],
        [5.9000, 3.0000, 4.2000, 1.5000],
        [6.0000, 2.9000, 4.5000, 1.5000],
        [6.7000, 3.0000, 5.2000, 2.3000],
        [5.7000, 2.9000, 4.2000, 1.3000],
        [6.7000, 3.3000, 5.7000, 2.1000],
        [5.1000, 3.3000, 1.7000, 0.5000],
        [5.5000, 2.6000, 4.4000, 1.2000],
        [4.4000, 3.2000, 1.3000, 0.2000],
        [6.4000, 2.8000, 5.6000, 2.1000]], dtype=torch.float64) tensor([0., 1., 1., 2., 1., 2., 0., 1., 0., 2.

In [140]:
model.train()
for epoch in range(200):
  batch_loss=0
  for i,batch in enumerate(batches):
    batch_X=batch[:,:-1].float()
    batch_Y=batch[:,-1].long()

    batchSgd.zero_grad()
    batch_yp=model(batch_X)
    loss=lossfn(batch_yp,batch_Y)
    loss.backward()
    batchSgd.step()
    batch_loss+=loss.item()
  print(f"Epoch {epoch+1}: Total Loss={batch_loss}")

Epoch 1: Total Loss=1.2745073367841542
Epoch 2: Total Loss=1.1311012571677566
Epoch 3: Total Loss=1.0670612172689289
Epoch 4: Total Loss=1.1581467567011714
Epoch 5: Total Loss=1.1918809220660478
Epoch 6: Total Loss=1.910055072628893
Epoch 7: Total Loss=1.0551149712409824
Epoch 8: Total Loss=1.2305973418988287
Epoch 9: Total Loss=1.3248081649653614
Epoch 10: Total Loss=1.2978423340246081
Epoch 11: Total Loss=1.1631989353336394
Epoch 12: Total Loss=1.2278738133609295
Epoch 13: Total Loss=1.3666975051164627
Epoch 14: Total Loss=1.09137580730021
Epoch 15: Total Loss=1.275722985388711
Epoch 16: Total Loss=1.4461175808683038
Epoch 17: Total Loss=0.999241973971948
Epoch 18: Total Loss=1.7226420282386243
Epoch 19: Total Loss=1.3331777900457382
Epoch 20: Total Loss=1.1319531397894025
Epoch 21: Total Loss=1.2495890255086124
Epoch 22: Total Loss=1.3431836236268282
Epoch 23: Total Loss=1.6909713367931545
Epoch 24: Total Loss=1.4745727428235114
Epoch 25: Total Loss=1.2983977899421006
Epoch 26: Tota

In [141]:
X=torch.FloatTensor(X)

In [142]:
soft=torch.softmax(model(X),dim=1)

In [147]:
torch.argmax(soft,dim=1)

tensor([0, 2, 2, 2, 1, 2, 1, 2, 2, 2])